Based on data analysis I decided to use only 6th feature, therefore now I am going to preprocess my data for model.


In [236]:
import pandas as pd
import numpy as np

In [237]:
train_dataset = pd.read_csv('../data/initital/internship_train.csv')
data_to_predict = pd.read_csv('../data/initital/internship_hidden_test.csv')

In [238]:
train_data = train_dataset[['6', 'target']]
data_to_predict = data_to_predict[['6']]

Now I'm goint to split my training data for train and valid data.

In [241]:
from sklearn.model_selection import train_test_split
train_data, test_data = train_test_split(train_data, random_state=1, test_size = 0.2)

In [244]:
import numpy as np
data_to_predict['1'] = np.random.rand(10000)

In [243]:
train_data.to_csv('../data/train_preprocessed/train_data.csv')
test_data.to_csv('../data/train_preprocessed/test_data.csv')
data_to_predict.to_csv('../data/predict_preprocessed/predict_data.csv')


Now I am going to read this to see if all work well.

In [45]:
import numpy as np
train_data = np.loadtxt('../data/train_preprocessed/train_data', delimiter=',', skiprows=1, usecols=[1, 2], dtype=np.float32)
test_data = np.loadtxt('../data/train_preprocessed/test_data', delimiter=',', skiprows=1, usecols=[1, 2], dtype=np.float32)
predict_data = np.loadtxt('../data/predict_preprocessed/predict_data', delimiter=',', skiprows=1, usecols=[0, 1], dtype=np.float32)

In [46]:
train_data

array([[ 9.539392 , 91.23334  ],
       [ 1.7320508,  3.027164 ],
       [-2.6457512,  7.1838913],
       ...,
       [ 7.81025  , 61.177536 ],
       [ 8.888194 , 79.91353  ],
       [-7.071068 , 50.23603  ]], dtype=float32)

In [47]:
test_data

array([[-5.196152 , 27.218664 ],
       [-7.5498343, 57.429962 ],
       [-8.062258 , 65.84673  ],
       ...,
       [-4.472136 , 20.555254 ],
       [-1.4142135,  2.1158175],
       [-8.124039 , 66.5579   ]], dtype=float32)

In [48]:
predict_data

array([[ 0.0000000e+00,  3.3166249e+00],
       [ 1.0000000e+00, -8.8881941e+00],
       [ 2.0000000e+00,  2.6457512e+00],
       ...,
       [ 9.9970000e+03,  4.6904159e+00],
       [ 9.9980000e+03,  4.0000000e+00],
       [ 9.9990000e+03,  9.5393925e+00]], dtype=float32)

So now I am going to create a model